export const DATEPICKER_CHANGE_STATE = 'DATEPICKER/CHANGE_STATE';
export const DATEPICKER_CLOSE_POPUP = 'DATEPICKER/CLOSE_POPUP';
export const DATEPICKER_SELECT_DATE = 'DATEPICKER/SELECT_DATE';
export const DATEPICKER_CHANGE_DATE = 'DATEPICKER/CHANGE_DATE';
export const DATEPICKER_SELECT_TOMORROW = 'DATEPICKER/SELECT_TOMORROW';
export const DATEPICKER_SELECT_YEAR = 'DATEPICKER/SELECT_YEAR';
export const DATEPICKER_CHANGE_VIEWMODE = 'DATEPICKER/CHANGE_VIEWMODE';
